# -*- coding: utf-8 -*-
"""QR Code generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g8r53Rg1SnAA7rwB7LkvPXVK6Z1nmyjv
"""

pip install qrcode[pil]

"""#Image to  qr generator"""

import qrcode
from PIL import Image

def generate_qr_code_from_image(image_path):
    img = Image.open(image_path)
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=10,
        border=4,
    )
    qr.add_data(img)
    qr.make(fit=True)
    qr_img = qr.make_image(fill_color="black", back_color="white")
    qr_img.save("generated_qr_code.png")

image_path = '/content/Egimg.jpg'
generate_qr_code_from_image(image_path)

"""#Link to QR generator"""

import qrcode as qr
img=qr.make("https://github.com/Singharunj20")
img.save("LinkQr.png")

import qrcode
from PIL import Image

qr=qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=10,
    border=4,
)
qr.add_data("https://github.com/Singharunj20")
qr.make(fit=True)
img=qr.make_image(fill_color="black",back_color="white")
img.save("LinkQr2.png")